### ISSUE TITLE
gs.gcplot.com down?

### ISSUE THREAD

**Issue by naiduarvind** [dmart28/gcplot#10]
Hi all,

I just setup a local GSPlot platform and setup the gcpc connector on my server where my JVM is running. 

However, upon starting I am hitting into this issue as shown from gcpc's log whereby the gs.gsplot.com URL is unknown.

![Screenshot 2019-04-08 at 4 21 43 PM](https://user-images.githubusercontent.com/6829472/55709287-93fd2080-5a1a-11e9-817a-f609dd6305c3.png)

Hitting the browser with this url https://gs.gcplot.com also yields the same result. 

![Screenshot 2019-04-08 at 4 23 25 PM](https://user-images.githubusercontent.com/6829472/55709332-ad9e6800-5a1a-11e9-9db0-138d0c984519.png)

Was there a change in the URL for the API server? I tried looking up subdomains but didn't see an entry for gs.gcplot.com as well.

Thanks.

**Comment by dmart28** [comment]
Hi @naiduarvind !

Thanks for the notice. The SSL certificate went expired, I'll try to fix the issue ASAP and will let you know when it'll be resolved. Thanks for your patience.

**Comment by dmart28** [comment]
Hi @naiduarvind !

Nevermind my previous comment, it was a mistake. Currently, gcpc util is out of support, since the gcplot went open source and I don't have free resources to make it work with Docker container.

**Comment by naiduarvind** [comment]
@dmart28 -- would it work if I spun up gcplot server and change the API endpoint to my own?

**Comment by dmart28** [comment]
Yes, you actually need reconfigure your gcpc instance to use your local S3 bucket, as well as configure GCPlot to use your bucket. Check:

- https://docs.gcplot.com/log-files-processing/connector-installation-and-configuration/configuration.html (GCP_HOST actually)

- https://docs.gcplot.com/log-files-processing/configuring-analyze.html

**Comment by naiduarvind** [comment]
Thanks @dmart28. Will close this issue now.
