### ISSUE TITLE
What's the meaning of  EMA in Heap used before EMA

### ISSUE THREAD

**Issue by jiacai2050** [dmart28/gcplot#9]
![image](https://user-images.githubusercontent.com/3848910/50718844-db4bdc00-10ce-11e9-98ce-d18fcd89ea82.png)

There is no explanation in [doc page](https://docs.gcplot.com/gcplot-overview/reports/memory.html)

**Comment by dmart28** [comment]
Hi!

It's an Exponential Moving Average of `Heap Used Before` data. You can read [here](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average) about it to get more detailed explanation.
